-- FBN (Fictitious Business Name) Data
CREATE TABLE IF NOT EXISTS raw_fbns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filing_number TEXT,
    business_name TEXT NOT NULL,
    street_address TEXT,
    city TEXT,
    state TEXT,
    zip_code TEXT NOT NULL,
    filing_date DATE NOT NULL,
    expiration_date DATE,
    owner_name TEXT,
    is_renewal BOOLEAN DEFAULT FALSE,
    category TEXT, -- 'Contractor', 'Investor', 'Service', or NULL
    raw_data JSONB, -- Full record from Socrata
    created_at TIMESTAMPTZ DEFAULT NOW(),
    source_id TEXT UNIQUE -- To prevent duplicates (e.g., Socrata ID or Filing Number)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_raw_fbns_zip ON raw_fbns(zip_code);
CREATE INDEX IF NOT EXISTS idx_raw_fbns_business_name ON raw_fbns(business_name);
CREATE INDEX IF NOT EXISTS idx_raw_fbns_filing_date ON raw_fbns(filing_date);
