-- 1. Crime Trends Table (for Security Brief)
CREATE TABLE IF NOT EXISTS crime_trends (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    district TEXT NOT NULL,
    category TEXT NOT NULL,
    count INT NOT NULL,
    rolling_8wk_avg FLOAT,
    status TEXT,
    sources JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(date, district, category)
);

-- 2. Permit Velocity Table (for Quarterly Trends)
CREATE TABLE IF NOT EXISTS permit_velocity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_ending DATE NOT NULL,
    zip TEXT NOT NULL,
    count INT NOT NULL,
    avg_value FLOAT,
    yoy_change FLOAT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(week_ending, zip)
);

-- 3. Recent Permits Table (for "Dumb Terminal" Display)
CREATE TABLE IF NOT EXISTS recent_permits (
    permit_number TEXT PRIMARY KEY,
    address TEXT,
    zip_code TEXT,
    apn TEXT,
    permit_type TEXT,
    description TEXT,
    issue_date DATE,
    status TEXT,
    valuation NUMERIC,
    zimas_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- 4. FBN (Fictitious Business Name) Table
CREATE TABLE IF NOT EXISTS raw_fbns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filing_number TEXT,
    business_name TEXT NOT NULL,
    street_address TEXT,
    city TEXT,
    state TEXT,
    zip_code TEXT NOT NULL,
    filing_date DATE NOT NULL,
    expiration_date DATE,
    owner_name TEXT,
    is_renewal BOOLEAN DEFAULT FALSE,
    category TEXT,
    raw_data JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    source_id TEXT UNIQUE
);



-- 5. Parcel Details (Assessor Data - Physical Attributes)
CREATE TABLE IF NOT EXISTS parcel_details (
    apn TEXT PRIMARY KEY, 
    ain TEXT,
    address TEXT,
    city TEXT,
    zip_code TEXT,
    year_built INT,
    sqft INT,
    units INT,
    bedrooms INT,
    bathrooms INT,
    assessed_value NUMERIC,
    zoning TEXT,
    use_code TEXT,
    use_type TEXT,
    raw_data JSONB,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- 6. Code Enforcement (LADBS "Neighborhood Standards")
CREATE TABLE IF NOT EXISTS code_enforcement (
    case_number TEXT PRIMARY KEY,
    address TEXT,
    case_type TEXT,  -- e.g. 'Building', 'Electrical', 'Zoning'
    violation_description TEXT,
    date_opened DATE,
    status TEXT, -- 'O' or 'C' (City uses 'Open', 'Closed' usually, will map in script)
    council_district INT,
    -- Note: 'days_open' can be calculated on read, but if user wants generated column:
    -- days_open INT GENERATED ALWAYS AS (CURRENT_DATE - date_opened) STORED, 
    -- Supabase/Postgres Generated Columns might need immutable functions. 
    -- Better to View-level or simple fetch calculation. 
    -- I will omit the generated column for simplicity and calc in UI/Query.
    lat float,
    lon float,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_code_enforcement_status ON code_enforcement(status);
CREATE INDEX IF NOT EXISTS idx_code_enforcement_date ON code_enforcement(date_opened);



