-- ============================================================================
-- Hills Ledger: rebuild missing schema on the claimed Supabase project
-- (elhtexcstngvgoyidtlc). The claim brought only the earliest tables
-- (areas/sources/events/projects/ingest_runs/watchlists); everything below
-- was added later via scattered migrations and ad-hoc scripts.
--
-- Run in: Supabase Dashboard -> SQL Editor. Idempotent: safe to run again.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 0. Columns the transferred base tables may be missing
-- ---------------------------------------------------------------------------
ALTER TABLE sources ADD COLUMN IF NOT EXISTS provider_key text;
CREATE INDEX IF NOT EXISTS idx_sources_provider_area ON sources(provider_key, area_id);
UPDATE sources SET provider_key = 'nws' WHERE provider_key IS NULL AND (name ILIKE '%nws%' OR name ILIKE '%weather%');
UPDATE sources SET provider_key = 'lafd' WHERE provider_key IS NULL AND name ILIKE '%lafd%';
UPDATE sources SET provider_key = 'ladbs' WHERE provider_key IS NULL AND (name ILIKE '%ladbs%' OR name ILIKE '%permit%');

ALTER TABLE events ADD COLUMN IF NOT EXISTS is_seed boolean DEFAULT false NOT NULL;
CREATE INDEX IF NOT EXISTS idx_events_is_seed ON events(is_seed);

-- ---------------------------------------------------------------------------
-- 1. neighborhood_intel — the core feed table (news, safety, sweeps)
--    RLS intentionally disabled (public read cache; service role writes)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS neighborhood_intel (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_name TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    url TEXT UNIQUE,
    category TEXT NOT NULL DEFAULT 'News',
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    priority INTEGER DEFAULT 3,
    incident_id TEXT,
    snapshot BOOLEAN DEFAULT FALSE,
    location TEXT,
    source_url TEXT,
    raw_json JSONB
);

CREATE INDEX IF NOT EXISTS idx_neighborhood_intel_category ON neighborhood_intel(category);
CREATE INDEX IF NOT EXISTS idx_neighborhood_intel_published ON neighborhood_intel(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_neighborhood_intel_source ON neighborhood_intel(source_name);
CREATE UNIQUE INDEX IF NOT EXISTS idx_intel_incident_id ON neighborhood_intel(incident_id) WHERE incident_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_neighborhood_intel_priority ON neighborhood_intel(priority);

-- ---------------------------------------------------------------------------
-- 2. Trends + permits + businesses + parcels + code enforcement
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS crime_trends (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    district TEXT NOT NULL,
    category TEXT NOT NULL,
    count INT NOT NULL,
    rolling_8wk_avg FLOAT,
    status TEXT,
    sources JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(date, district, category)
);

CREATE TABLE IF NOT EXISTS permit_velocity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_ending DATE NOT NULL,
    zip TEXT NOT NULL,
    count INT NOT NULL,
    avg_value FLOAT,
    yoy_change FLOAT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(week_ending, zip)
);

CREATE TABLE IF NOT EXISTS recent_permits (
    permit_number TEXT PRIMARY KEY,
    address TEXT,
    zip_code TEXT,
    apn TEXT,
    permit_type TEXT,
    description TEXT,
    issue_date DATE,
    status TEXT,
    valuation NUMERIC,
    zimas_url TEXT,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    coords_missing BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
-- In case the table pre-existed without the later columns:
ALTER TABLE recent_permits
  ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS lon DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS coords_missing BOOLEAN DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_recent_permits_zip ON recent_permits(zip_code);
CREATE INDEX IF NOT EXISTS idx_recent_permits_lat_lon ON recent_permits(lat, lon);

CREATE TABLE IF NOT EXISTS raw_fbns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filing_number TEXT,
    business_name TEXT NOT NULL,
    street_address TEXT,
    city TEXT,
    state TEXT,
    zip_code TEXT NOT NULL,
    filing_date DATE NOT NULL,
    expiration_date DATE,
    owner_name TEXT,
    is_renewal BOOLEAN DEFAULT FALSE,
    category TEXT,
    raw_data JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    source_id TEXT UNIQUE
);

CREATE INDEX IF NOT EXISTS idx_raw_fbns_zip ON raw_fbns(zip_code);
CREATE INDEX IF NOT EXISTS idx_raw_fbns_business_name ON raw_fbns(business_name);
CREATE INDEX IF NOT EXISTS idx_raw_fbns_filing_date ON raw_fbns(filing_date);

CREATE TABLE IF NOT EXISTS parcel_details (
    apn TEXT PRIMARY KEY,
    ain TEXT,
    address TEXT,
    city TEXT,
    zip_code TEXT,
    year_built INT,
    sqft INT,
    units INT,
    bedrooms INT,
    bathrooms INT,
    assessed_value NUMERIC,
    zoning TEXT,
    use_code TEXT,
    use_type TEXT,
    raw_data JSONB,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS code_enforcement (
    case_number TEXT PRIMARY KEY,
    address TEXT,
    case_type TEXT,
    violation_description TEXT,
    date_opened DATE,
    status TEXT,
    council_district INT,
    lat float,
    lon float,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_code_enforcement_status ON code_enforcement(status);
CREATE INDEX IF NOT EXISTS idx_code_enforcement_date ON code_enforcement(date_opened);

-- ---------------------------------------------------------------------------
-- 3. BuildWatch inspections (real estate page)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS recent_inspections (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source TEXT NOT NULL DEFAULT 'ladbs_inspections',
    source_row_id TEXT UNIQUE NOT NULL,
    permit TEXT,
    address_text TEXT,
    inspection_type TEXT,
    inspection_result TEXT,
    permit_status TEXT,
    inspection_date TIMESTAMPTZ,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    location JSONB,
    result_class TEXT NOT NULL DEFAULT 'neutral',
    is_failure BOOLEAN NOT NULL DEFAULT FALSE,
    severity TEXT NOT NULL DEFAULT 'low',
    raw JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_recent_inspections_date ON recent_inspections (inspection_date DESC);
CREATE INDEX IF NOT EXISTS idx_recent_inspections_coords ON recent_inspections (lat, lon);
CREATE INDEX IF NOT EXISTS idx_recent_inspections_failure ON recent_inspections (is_failure, inspection_date DESC);
CREATE INDEX IF NOT EXISTS idx_recent_inspections_result_class ON recent_inspections (result_class);

-- ---------------------------------------------------------------------------
-- 4. FireScore (real estate page): PostGIS zones + point lookup RPC
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS fire_zones (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source TEXT NOT NULL,
    zone_class TEXT NOT NULL,
    geom GEOGRAPHY(MULTIPOLYGON, 4326) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    raw JSONB
);

CREATE INDEX IF NOT EXISTS idx_fire_zones_geom ON fire_zones USING GIST (geom);
CREATE INDEX IF NOT EXISTS idx_fire_zones_class ON fire_zones (zone_class);

ALTER TABLE fire_zones ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "Public read access" ON fire_zones FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Service role full access" ON fire_zones USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE OR REPLACE FUNCTION get_fire_zone(lat DOUBLE PRECISION, lon DOUBLE PRECISION)
RETURNS TABLE (zone_class TEXT, source TEXT)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT f.zone_class, f.source
    FROM fire_zones f
    WHERE ST_Covers(f.geom, ST_SetSRID(ST_MakePoint(lon, lat), 4326)::geography)
    ORDER BY
        CASE f.zone_class
            WHEN 'VERY_HIGH' THEN 1
            WHEN 'HIGH' THEN 2
            ELSE 3
        END
    LIMIT 1;
END;
$$;

-- ---------------------------------------------------------------------------
-- 5. Address watchlist + user prefs (real estate page)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS watch_addresses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  label TEXT,
  address_text TEXT NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  lon DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_watch_addresses_user_id ON watch_addresses(user_id);
CREATE INDEX IF NOT EXISTS idx_watch_addresses_user_created ON watch_addresses(user_id, created_at DESC);

ALTER TABLE watch_addresses ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "select_own_watch_addresses" ON watch_addresses FOR SELECT USING (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "insert_own_watch_addresses" ON watch_addresses FOR INSERT WITH CHECK (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "update_own_watch_addresses" ON watch_addresses FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "delete_own_watch_addresses" ON watch_addresses FOR DELETE USING (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS user_prefs (
  user_id UUID PRIMARY KEY,
  default_watch_address_id UUID REFERENCES watch_addresses(id) ON DELETE SET NULL,
  default_radius_m INT DEFAULT 500,
  default_window_days INT DEFAULT 30,
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE user_prefs ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "select_own_user_prefs" ON user_prefs FOR SELECT USING (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "insert_own_user_prefs" ON user_prefs FOR INSERT WITH CHECK (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "update_own_user_prefs" ON user_prefs FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ---------------------------------------------------------------------------
-- 6. Watchlists write policies (table exists from the base schema)
-- ---------------------------------------------------------------------------
DO $$ BEGIN
  CREATE POLICY "Users can insert own watchlist terms" ON watchlists FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY "Users can delete own watchlist terms" ON watchlists FOR DELETE TO authenticated USING (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ---------------------------------------------------------------------------
-- Done. Verify:
-- ---------------------------------------------------------------------------
SELECT table_name FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;
